apiVersion: v1
kind: Secret
metadata:
  name: umbrella-secrets
  namespace: umbrella
  labels:
    app: umbrella
    environment: ${ENVIRONMENT}
    managed-by: spring-boot
type: Opaque
data:
  # Primary Database Credentials (SQL Server)
  PRIMARY_DB_URL: ${base64:DB_URL}
  PRIMARY_DB_USER: ${base64:DB_USERNAME}
  PRIMARY_DB_PASSWORD: ${base64:DB_PASSWORD}
  PRIMARY_DB_HIKARI_MIN_IDLE: ${base64:5}
  PRIMARY_DB_HIKARI_MAX_POOL: ${base64:50}

  # Secondary Database Credentials (DB2)
  SECONDARY_DB_URL: ${base64:DB2_URL}
  SECONDARY_DB_USER: ${base64:DB2_USERNAME}
  SECONDARY_DB_PASSWORD: ${base64:DB2_PASSWORD}
  SECONDARY_DB_HIKARI_MIN_IDLE: ${base64:3}
  SECONDARY_DB_HIKARI_MAX_POOL: ${base64:30}

  # JWT Configuration
  JWT_SECRET: ${base64:JWT_SECRET}
  JWT_EXPIRATION: ${base64:86400000}
  JWT_REFRESH_EXPIRATION: ${base64:604800000}
  JWT_ISSUER: ${base64:umbrella-auth}

  # Integration Endpoints
  POLICYSTAR_URL: ${base64:POLICYSTAR_URL}
  POLICYSTAR_CREDENTIALS: ${base64:POLICYSTAR_CREDENTIALS}
  POLICYSTAR_TIMEOUT: ${base64:30000}

  RMV_URL: ${base64:RMV_URL}
  RMV_API_KEY: ${base64:RMV_API_KEY}
  RMV_TIMEOUT: ${base64:20000}

  SPEEDPAY_URL: ${base64:SPEEDPAY_URL}
  SPEEDPAY_CREDENTIALS: ${base64:SPEEDPAY_CREDENTIALS}
  SPEEDPAY_TIMEOUT: ${base64:25000}

  CLUE_URL: ${base64:CLUE_URL}
  CLUE_API_KEY: ${base64:CLUE_API_KEY}
  CLUE_TIMEOUT: ${base64:20000}

  # Spring Boot Actuator Security
  ACTUATOR_USERNAME: ${base64:ACTUATOR_USERNAME}
  ACTUATOR_PASSWORD: ${base64:ACTUATOR_PASSWORD}

  # Connection Pool Configuration
  HIKARI_POOL_COMMON: |-
    ${base64:
      auto-commit: true
      connection-timeout: 20000
      validation-timeout: 5000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      register-mbeans: true
    }