apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umbrella.fullname" . }}
  labels:
    {{- include "umbrella.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  # Primary Database Credentials (SQL Server)
  SPRING_DATASOURCE_PRIMARY_URL: {{ printf "jdbc:sqlserver://%s:%s;databaseName=%s" .Values.backend.database.primary.host .Values.backend.database.primary.port .Values.backend.database.primary.name | b64enc | quote }}
  SPRING_DATASOURCE_PRIMARY_USERNAME: {{ .Values.backend.database.primary.username | b64enc | quote }}
  SPRING_DATASOURCE_PRIMARY_PASSWORD: {{ .Values.backend.database.primary.password | b64enc | quote }}
  SPRING_DATASOURCE_PRIMARY_DRIVER_CLASS_NAME: {{ "com.microsoft.sqlserver.jdbc.SQLServerDriver" | b64enc | quote }}

  # Secondary Database Credentials (DB2)
  SPRING_DATASOURCE_SECONDARY_URL: {{ printf "jdbc:db2://%s:%s/%s" .Values.backend.database.secondary.host .Values.backend.database.secondary.port .Values.backend.database.secondary.name | b64enc | quote }}
  SPRING_DATASOURCE_SECONDARY_USERNAME: {{ .Values.backend.database.secondary.username | b64enc | quote }}
  SPRING_DATASOURCE_SECONDARY_PASSWORD: {{ .Values.backend.database.secondary.password | b64enc | quote }}
  SPRING_DATASOURCE_SECONDARY_DRIVER_CLASS_NAME: {{ "com.ibm.db2.jcc.DB2Driver" | b64enc | quote }}

  # Security Configuration
  SPRING_SECURITY_JWT_SECRET_KEY: {{ .Values.backend.security.jwt.secretKey | b64enc | quote }}
  SPRING_SECURITY_JWT_EXPIRATION: {{ .Values.backend.security.jwt.expiration | default "86400" | b64enc | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SECRET: {{ .Values.backend.security.oauth2.clientSecret | b64enc | quote }}

  # Integration Service Keys
  INTEGRATION_POLICYSTAR_API_KEY: {{ .Values.backend.integration.policystar.apiKey | b64enc | quote }}
  INTEGRATION_POLICYSTAR_API_URL: {{ .Values.backend.integration.policystar.apiUrl | b64enc | quote }}
  
  INTEGRATION_RMV_SERVICE_KEY: {{ .Values.backend.integration.rmv.serviceKey | b64enc | quote }}
  INTEGRATION_RMV_SERVICE_URL: {{ .Values.backend.integration.rmv.serviceUrl | b64enc | quote }}
  
  INTEGRATION_SPEEDPAY_API_KEY: {{ .Values.backend.integration.speedpay.apiKey | b64enc | quote }}
  INTEGRATION_SPEEDPAY_API_URL: {{ .Values.backend.integration.speedpay.apiUrl | b64enc | quote }}
  
  INTEGRATION_CLUE_PROPERTY_API_KEY: {{ .Values.backend.integration.clueProperty.apiKey | b64enc | quote }}
  INTEGRATION_CLUE_PROPERTY_API_URL: {{ .Values.backend.integration.clueProperty.apiUrl | b64enc | quote }}

  # Spring Boot Actuator Security
  MANAGEMENT_SECURITY_API_KEY: {{ .Values.backend.management.security.apiKey | b64enc | quote }}

  # Connection Pool Configuration
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: {{ .Values.backend.database.connectionPool.maxPoolSize | default "10" | b64enc | quote }}
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: {{ .Values.backend.database.connectionPool.minIdle | default "5" | b64enc | quote }}
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: {{ .Values.backend.database.connectionPool.idleTimeout | default "300000" | b64enc | quote }}

  # Logging Configuration
  LOGGING_LEVEL_ROOT: {{ .Values.backend.logging.rootLevel | default "INFO" | b64enc | quote }}
  LOGGING_PATTERN_CONSOLE: {{ .Values.backend.logging.consolePattern | b64enc | quote }}