apiVersion: v1
kind: Secret
metadata:
  name: umbrella-secrets
  namespace: umbrella
  labels:
    app: umbrella
    environment: ${ENVIRONMENT}
    component: configuration
    managed-by: spring-boot
type: Opaque
data:
  # Primary Database Configuration (SQL Server with HikariCP)
  spring.datasource.primary.url: ${base64:DB_URL}
  spring.datasource.primary.username: ${base64:DB_USERNAME}
  spring.datasource.primary.password: ${base64:DB_PASSWORD}
  spring.datasource.primary.hikari.maximum-pool-size: ${base64:50}
  spring.datasource.primary.hikari.minimum-idle: ${base64:10}
  spring.datasource.primary.hikari.connection-timeout: ${base64:20000}
  spring.datasource.primary.hikari.idle-timeout: ${base64:300000}
  spring.datasource.primary.hikari.pool-name: ${base64:PrimaryHikariPool}

  # Secondary Database Configuration (DB2 with HikariCP)
  spring.datasource.secondary.url: ${base64:DB2_URL}
  spring.datasource.secondary.username: ${base64:DB2_USERNAME}
  spring.datasource.secondary.password: ${base64:DB2_PASSWORD}
  spring.datasource.secondary.hikari.maximum-pool-size: ${base64:30}
  spring.datasource.secondary.hikari.minimum-idle: ${base64:5}
  spring.datasource.secondary.hikari.connection-timeout: ${base64:20000}
  spring.datasource.secondary.hikari.idle-timeout: ${base64:300000}
  spring.datasource.secondary.hikari.pool-name: ${base64:SecondaryHikariPool}

  # Spring Security JWT Configuration
  spring.security.jwt.secret: ${base64:JWT_SECRET}
  spring.security.jwt.refresh-token-secret: ${base64:JWT_REFRESH_SECRET}
  spring.security.jwt.expiration: ${base64:86400000}
  spring.security.jwt.refresh-token-expiration: ${base64:604800000}
  spring.security.jwt.issuer: ${base64:umbrella-auth}

  # Integration Endpoint Configurations
  spring.integration.policystar.url: ${base64:POLICYSTAR_URL}
  spring.integration.policystar.credentials: ${base64:POLICYSTAR_CREDENTIALS}
  spring.integration.policystar.timeout: ${base64:30000}
  spring.integration.policystar.retry.max-attempts: ${base64:3}
  spring.integration.policystar.retry.backoff: ${base64:1000}

  spring.integration.rmv.url: ${base64:RMV_URL}
  spring.integration.rmv.api-key: ${base64:RMV_API_KEY}
  spring.integration.rmv.timeout: ${base64:20000}

  spring.integration.speedpay.url: ${base64:SPEEDPAY_URL}
  spring.integration.speedpay.credentials: ${base64:SPEEDPAY_CREDENTIALS}
  spring.integration.speedpay.timeout: ${base64:25000}

  spring.integration.clue.url: ${base64:CLUE_URL}
  spring.integration.clue.api-key: ${base64:CLUE_API_KEY}
  spring.integration.clue.timeout: ${base64:20000}

  # Spring Boot Actuator Security Configuration
  management.endpoints.web.exposure.include: ${base64:health,metrics,prometheus}
  management.endpoints.web.exposure.exclude: ${base64:env,beans}
  management.endpoints.web.base-path: ${base64:/actuator}
  management.endpoints.web.security.username: ${base64:ACTUATOR_USERNAME}
  management.endpoints.web.security.password: ${base64:ACTUATOR_PASSWORD}

  # Virtual Threads Configuration (Java 21)
  spring.threads.virtual.enabled: ${base64:true}
  spring.threads.virtual.pool-size: ${base64:250}

  # Common HikariCP Configuration
  spring.datasource.hikari.common-config: |-
    ${base64:
      auto-commit: true
      connection-timeout: 20000
      validation-timeout: 5000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      register-mbeans: true
    }